### ISSUE TITLE
Slette ppa.nais.io

### ISSUE THREAD

**Issue by mortenlj** [nais/nais-ppa#15]
Når alle har migrert over til å bruke GAR for linux pakkene så kan vi avvikle/slette ppa.nais.io aka https://github.com/nais/nais-ppa.

**Comment by sechmann** [comment]
Er det mulig å se når «alle» har migrert? Har vi usage stats?

**Comment by mortenlj** [comment]
> Er det mulig å se når «alle» har migrert? Har vi usage stats?

Tror ikke vi har noe, så det er sikkert litt vanskelig. Måtte være hvis Github har noe "pages-statistikk" eller noe, men ikke noe jeg har hørt om. Noe av oppgaven her må jo nesten bli å finne ut hvordan vi vet om den kan gjøres :smile:

**Comment by mortenlj** [comment]
Kan kanskje lese noe ut av disse grafene: https://github.com/nais/nais-ppa/graphs/traffic

**Comment by sechmann** [comment]
Tenker egentlig vi bare sletter, med en påminnelse på slack til linux-kanalen. Dette vil dukke opp som feilmeldinger neste gang man kjører `apt update` så folk får det med seg.

**Comment by sechmann** [comment]
stoppa publisering fra nais/cli nais/narcos nais/device nå

**Comment by sechmann** [comment]
pages deaktivert, arkiverer repo
